### ISSUE TITLE
Customize the pipe name

### ISSUE THREAD

**Issue by jmhickman** [Kevin-Robertson/Invoke-TheHash#11]
So I tried fussing around in the code  to change the name of the pipe from \svcctl  to a different value. My test target is SMB2, so I didn't fuss with the pipe name encoded in the SMB1 section. I put the nulls in to account for the UTF-16LE. However, when I run the script, I just get:

```
Hash being used: 79D6ED02F83D0E3862B2755AB5487933
user successfully authenticated on <machinename>
Something went wrong with <machinename>
```
I saw this $SMB_named_pipe_UUID value, but when I tried to decode it I just got binary-looking gibberish. Do I need to change this value as well? And if so, how do I derive the correct value?

Any pointers would be appreciated.

**Comment by Kevin-Robertson** [comment]
The $SMB_named_pipe_UUID (current version $named_pipe_UUID) value is the byte representation of the RCP interface UUID 367ABB81-9844-35F1-AD32-98F038001003.
https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-scmr/e7a38186-cde2-40ad-90c7-650822bd6333

It's been awhile since I messed around with that. Two things, if I remember correctly, only the SVCCTL pipe will work for what Invoke-SMBExec does. Second, since I'm not relying on a full protocol implementation, I cheated everywhere I could:) So, that code can't always be easily modified. I'd recommend, if possible, getting a packet capture that is close what you want to do and then work back from there.

**Comment by jmhickman** [comment]
Aaah, alrighty, I get it. I didn't realize the functionality was dependent on a specific pipe name. I read a post from Red Canary a while back that talked about some other projects allowing modifications to their pipe names for their psexec implementations, so I just assumed it would apply here as well. 

Thanks for getting back to me so quickly, and thanks for the code. I learned a little bit about the protocol reading your stuff. :)
