### ISSUE TITLE
Question: use Invoke-WMIExec to query stuff

### ISSUE THREAD

**Issue by cfalta** [Kevin-Robertson/Invoke-TheHash#3]
Hi Kevin,

thanks for sharing your work, it really is a great tool.

I figured it would be interesting to tweak Invoke-WMIExec so it can also query stuff via WMI and not only execute. I had a look at the source code but I couldn't quite figure out where you define the actual WMI class you use for command execution ("Win32_Process" ?). Could you point me in the right direction?

Thanks in advance!

Christoph

**Comment by Kevin-Robertson** [comment]
Hi Christoph,

Thanks for the interest! Basically, Invoke-WMIExec was built at the packet level. I started with a packet capture from Invoke-WmiMethod. You won't find a lot of the normal PowerShell WMI code. It's just a basic WMI client that does as little as possible (in this case, command execution). I went from the ground up so that I could control the auth process.

I'd start by comparing packet captures between the WMI queries and Invoke-WMIExec. That should give you an indicator of where you need to start modifying things. It's probably going to be much easier to just create a dedicated query module.

**Comment by cfalta** [comment]
Hi Kevin,

Thanks for the quick response, I'll have a look into it.
