### ISSUE TITLE
SMB enumeration exception then ran with Invoke-TheHash

### ISSUE THREAD

**Issue by Vokaysh** [Kevin-Robertson/Invoke-TheHash#8]
So it seems Invoke-SMBEnum fails when passing target inputs that are processed in Invoke-TheHash, but not when a single target is passed directly to Invoke-SMBEnum.

![image](https://user-images.githubusercontent.com/18655125/49646122-db50b180-fa26-11e8-90bd-b614ce636ddd.png)

So when debugging I can see in Get-TargetList the $target_list.Add($entry) line actually adds a string, which is the correct type.

However when checking the target type later in the flow it's an object array which errors out when attempting to convert to String when passed to Invoke-SMBEnum.

I have no idea about this powershell voodoo, but a quick fix I found is to manually convert to string before passing to Invoke-SMBEnum.

Note I have not tested other functions (SMBClient, SMBExec, etc.), just needed this one to work on a pentest.

**Comment by Kevin-Robertson** [comment]
Thanks for finding the bug. It looks like when I removed the plural from the old [Array]$Targets parameter I caused a type conflict further down in the code due to reusing $Target. Powershell 2 doesn't complain but new versions do.

The fix I found is to just change all the $target variables from line 264 to the end to $target_host. Do you want to test and update your PR? The "| Out-String).trim()" probably isn't needed after changing the variable name.

**Comment by Vokaysh** [comment]
Ah so it retains its type, that makes sense. Very cool, thanks for checking it out! Updated the PR.

Also thanks for your work with this project and Inveigh, very helpful. :)

**Comment by Kevin-Robertson** [comment]
Merged, thanks again for finding the bug!
